name: taqo_cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  taqo_common:
    path: ../taqo_common
  taqo_event_server_protocol:
    path: ../taqo_event_server_protocol

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
