name: taqo_event_server_protocol
description: A client/server library for Taqo event server protocol.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  taqo_common:
    path: '../taqo_common'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
