name: time_zone_notifier
description: Flutter plugin for getting time zone change callbacks
version: 0.0.1
homepage: https://github.com/BobEvans/taqo_survey

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.taqo.survey.timezonenotifier
        pluginClass: TimeZoneNotifierPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
