name: data_binding_builder
description: A lib for generating data binding code for taqo.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  build:
  dart_style:


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

