name: taqo_common
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  glob: ^1.2.0
  intl: ^0.16.1
  json_annotation: ^3.0.1
  logging: ^0.11.4
  petitparser: ^2.4.0
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11+1
dev_dependencies:
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  test: any
