# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: taqo_common
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  glob: ^2.0.0
  intl: ^0.16.1
  json_annotation: ^3.0.1
  logging: ^0.11.4
  petitparser: ^2.4.0
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11+1
  collection: ^1.15.0-nullsafety.4
dev_dependencies:
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  test: any

# TODO(https://github.com/google/taqo-paco/issues/142):
# Remove the dependency overrides after migrationg to null-safe Dart, since these are all
# workarounds to fix broken dependencies due to lack/mix of null-safety support.
dependency_overrides:
  meta: 1.6.0
  # To make build_runner work, we need newer analyzer that supports Dart 2.14
  analyzer: ^1.0.0
